# Generated by Django 3.1.4 on 2020-12-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
    ]
